#% text_encoding = iso8859_1

:external_name          Professional - Smallworld Core
:description        Professional application using application framework architecture
:addresses	        Addresses
:cadastral	        Cadastral
:details	        Details
:geometry	        Geometry
:show_pubs              Show Pubs
:pubs			Public Houses
:gis			Geographic
:drawing		Drawing
:internals		Substation Internals
