#% text_encoding = iso8859_1

:eq	is
:neq	is not
:gt	greater than
:lt	less than
:le	less than or equals
:ge	greater than or equals

:route_finder			Routefinder
:route_finder_description	Finds the shortest path between two nodes in the Road network.

:no_motorways			Avoid motorways
:no_roundabouts			Avoid roundabouts
:no_road_works			Avoid roadworks
:no_a_roads			Avoid A-Roads
:no_dual_carriageway		Avoid dual carriageway
:cost_message			Cost calculation
:distance			Distance
:time				Travel time
:min_road			Road
:road_type			Road Type
